### ISSUE TITLE
Add to chrome webstore

### ISSUE THREAD

**Issue by AMeng** [dankrause/chrome-pagerduty#4]
This is amazing. Please add it to the chrome webstore for easier installation and updates.

**Comment by dankrause** [comment]
This can now be found on the Chrome Web Store here: https://chrome.google.com/webstore/detail/pagerduty/oanhanoldedeflnpnjokeeaeggkambcl

It may not be discoverable there yet without the link (can't search for it on the store), but I'm lead to believe it should be shortly.
